theme: jekyll-theme-slate
title: Make your Microservices sing!
description: Presentation and code examples from Oracle Code Sydney
repository: rubiconred/oracle-code
show_downloads: false
google_analytics: UA-35856338-6
